# OpenShift BuildConfig to build and push image to Quay.io
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ai-assistant-app-build
spec:
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/ai-assistant/ai-assistant-app:latest
    pushSecret:
      name: builder-dockercfg-qpsp8
  triggers:
    - type: ConfigChange
    - type: ImageChange
