apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-assistant

resources:
  - service.yaml
  - deployment.yaml
  - buildconfig.yaml
  - route.yaml
  - configmap.yaml
  - secret.yaml
  - rag-service.yaml
  - rag-imagestream.yaml
  - rag-pvc.yaml
  - rag-buildconfig.yaml
  - rag-deployment.yaml

# Patches to update cluster-specific values
patches:
  # Update VLLM_API_URL in main deployment
  - target:
      kind: Deployment
      name: ai-assistant-app
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: https://vllm-composer-ai-apps.apps.cluster-lp5sl.lp5sl.sandbox803.opentlc.com/v1/completions

  # Update image pull secret in main deployment
  - target:
      kind: Deployment
      name: ai-assistant-app
    patch: |-
      - op: replace
        path: /spec/template/spec/imagePullSecrets/0/name
        value: builder-dockercfg-sfkmz

  # Update push secret in buildconfig
  - target:
      kind: BuildConfig
      name: ai-assistant-app-build
    patch: |-
      - op: replace
        path: /spec/output/pushSecret/name
        value: builder-dockercfg-sfkmz

  # Update image pull secret in RAG deployment
  - target:
      kind: Deployment
      name: rag-service
    patch: |-
      - op: replace
        path: /spec/template/spec/imagePullSecrets/0/name
        value: builder-dockercfg-sfkmz

# Replacements for dynamic values (alternative to patches)
replacements:
  - source:
      kind: ConfigMap
      name: cluster-config
      fieldPath: data.CLUSTER_DOMAIN
    targets:
      - select:
          kind: Route
        fieldPaths:
          - spec.host
        options:
          delimiter: '.'
          index: 0

configMapGenerator:
  - name: cluster-config
    literals:
      - CLUSTER_DOMAIN=apps.cluster-lp5sl.lp5sl.sandbox803.opentlc.com
      - IMAGE_PULL_SECRET=builder-dockercfg-sfkmz
      - VLLM_API_URL=https://vllm-composer-ai-apps.apps.cluster-lp5sl.lp5sl.sandbox803.opentlc.com/v1/completions
