apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-service-cache-pvc
  namespace: ai-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Adjust size based on your model needs
