apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ran-simulator
  labels:
    app: ran-simulator
spec:
  output:
    to:
      kind: ImageStreamTag
      name: ran-simulator:latest
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers:
  - type: ConfigChange
  - type: ImageChange
