apiVersion: v1
kind: Service
metadata:
  name: ran-simulator
  labels:
    app: ran-simulator
spec:
  type: ClusterIP
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: ran-simulator
